version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.6
      - image: circleci/postgres:15.4
        environment:
          POSTGRES_USER: $TEST_DB_USER
          POSTGRES_DB: $TEST_DB_NAME
          POSTGRES_PASSWORD: $TEST_DB_PASS
    working_directory: ~/Task-management-backend
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Wait for Postgres
          command: |
            echo "Waiting for Postgres to be ready..."
            for i in {1..20}; do
              pg_isready -h localhost -p 5432 && break
              sleep 1
            done
      - run:
          name: Create test database
          command: psql -h localhost -U $TEST_DB_USER -c "CREATE DATABASE $TEST_DB_NAME;" || true
      - run:
          name: Run migrations
          command: npx sequelize db:migrate --env test
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Upload coverage to Coveralls
          command: npm run coverage
          environment:
            COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN

workflows:
  version: 2
  test-and-cover:
    jobs:
      - test