version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  test:
    docker:
      - image: cimg/node:20.6
    working_directory: ~/Task-management-backend
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Tests & Upload Coverage
          command: |
            npm run test
            nyc report --reporter=lcov | coveralls

workflows:
  version: 2
  test:
    jobs:
      - test
